name = "dot_js_test"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

target = "javascript"

[dependencies]
dot_env = { path = "../dotenv" }
gleam_stdlib = ">= 0.38.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
